/*
*  Copyright (C) 2013 The OmniROM Project
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*/

package com.android.settings.beanstalk.backup;

import android.util.Log;

import java.io.File;
import java.util.Date;

/**
* Represents a single backup consisting of an android backup file and an optional info file.
*
* The file names are expected to be in the format "packagename-timestamp.ab" and
* "packagename-timestamp.info", with timestamp being milliseconds since epoch.
*
* The .ab file is a file generated by the android backup service ("adb backup"),
* while the .info file is an optional text file with content like this:
* <pre>
* {@code
* label: Settings
* versionName: 1.0.0
* }
* </pre>
*
* Backup files are handled through {@link BackupManager}.
*
*/
public class Backup {

    public static final String BACKUP_FILE_TYPE = ".ab";

    public static final String INFO_FILE_TYPE = ".info";

    /**
    * The key in the value file prepending the app label.
    */
    public static final String KEY_LABEL = "label";

    /**
    * The key in the value file prepending the version name.
    */
    public static final String KEY_VERSION_NAME = "version_name";

    /**
    * The package name of the backed up package.
    */
    public final String packageName;

    /**
    * The file containing the backup.
    */
    public final String fileName;

    /**
    * Date the backup was taken.
    */
    public final Date date;

    /**
    * Total size of the backup.
    */
    public final long size;

    /**
    * The value of the application label tag in the app's manifest.
    */
    public final String label;

    /**
    * The value of the versionName tag in the app's manifest.
    */
    public final String versionName;

    /**
    * Constructs a backup representing an Android Backup that already
    * exists on the file system.
    */
    public Backup(String packageName, String fileName, long timestamp, long size,
            String label, String versionName) {
        this.packageName = packageName;
        this.fileName = fileName;
        this.date = new Date(timestamp);
        this.size = size;
        this.label = label;
        this.versionName = versionName;
    }

}
